### ISSUE TITLE
save deblur image in eval phase

### ISSUE THREAD

**Issue by YellowOrz** [chosj95/MIMO-UNet#11]
In [line 53 of eval.py](https://github.com/chosj95/MIMO-UNet/blob/4a523544e3c5192f5305610b761ee3a4d5d74648/eval.py#L53)(show as below), the output tensor is turned to PIL image after adding 0.5/255, then is saved. Why is this? This tensor has already been clipped to 0-1. I can't find the same processing way in the official document of torchvision
```python
if args.save_image:
    save_name = os.path.join(args.result_dir, name[0])
    pred_clip += 0.5 / 255
    pred = F.to_pil_image(pred_clip.squeeze(0).cpu(), 'RGB')
    pred.save(save_name)
```

**Comment by chosj95** [comment]
Hi,
I intended to round off the float numbers before multiplying by 255.

In the ```F.to_pil_image()``` , the clipped image is multiplied by 255 and applied floor operation as follows:
```
if isinstance(pic, torch.Tensor):
    if pic.is_floating_point() and mode != 'F':
        pic = pic.mul(255).byte()
    npimg = np.transpose(pic.cpu().numpy(), (1, 2, 0))
```

I think it needs an additional clip function to make it exactly as we intended because the range of the input of ```byte()``` function is 0-255 (8bit).

The correct saving code should be as follows:

```
if args.save_image:
    save_name = os.path.join(args.result_dir, name[0])
    pred_clip += 0.5 / 255
    pred_clip = torch.clamp(pred_clip, 0, 1)
    pred = F.to_pil_image(pred_clip.squeeze(0).cpu(), 'RGB')
    pred.save(save_name)
```
This code will be reflected soon, and I hope I have answered all of your questions.
