### ISSUE TITLE
When training model, the error is as follows:" No such file or directory: 'dataset/GOPRO\\valid\\blur\\'"

### ISSUE THREAD

**Issue by BingY998** [chosj95/MIMO-UNet#13]
Hello, when I was training MIMO-UNet model, I needed a verification set after 100 training epochs. Could you tell me how to make the verification set? The error is as follows: No such file or directory: 'dataset/GOPRO\\valid\\blur\\'

**Comment by star42154** [comment]
Hello, I also encountered the same problem, have you solved it?

**Comment by chosj95** [comment]
Hello, sorry for the late response and incomplete code.

Since the GoPro dataset does not provide a separate validation dataset,  we used the test dataset for validation. 

If you want to use the part (or whole) of the test set for validation, you just make a directory of the ```dataset/GOPRO/valid``` and copy some (or whole) of the blurry and sharp paired images of the test data to ```data/GOPRO/valid/blur``` and ```data/GOPRO/valid/sharp```, respectively.

Or in order to validate on entire testset, simply replace ```DeblurDataset(os.path.join(path, 'valid'))``` to   ```DeblurDataset(os.path.join(path, 'test'))``` in [Line 47](https://github.com/chosj95/MIMO-UNet/blob/main/data/data_load.py#L47.) of ```data/data_load.py```.

**Comment by star42154** [comment]
> 您好，抱歉回复晚了和代码不完整。
> 
> 由于 GoPro 数据集没有提供单独的验证数据集，我们使用测试数据集进行验证。
> 
> 如果您想使用测试集的一部分（或全部）进行验证，您只需创建一个目录`dataset/GOPRO/valid`并将部分（或全部）测试数据的模糊和清晰配对图像分别复制到`data/GOPRO/valid/blur`和`data/GOPRO/valid/sharp`。
> 
> 或者为了验证对整个测试集，只需更换`DeblurDataset(os.path.join(path, 'valid'))`到 `DeblurDataset(os.path.join(path, 'test'))`在[第47行](https://github.com/chosj95/MIMO-UNet/blob/main/data/data_load.py#L47.)的`data/data_load.py`。
Thank you for your answer,and  your answer has helped me solve the problem.

**Comment by star42154** [comment]
Thank you for your answer, and your answer has helped me solve the problem.

**Comment by BingY998** [comment]
Thanks！
